demo: 
  one: 1
  two: 2
  three: 3
#person: 
#  name: ${random.value}
#  age: ${random.int[1,10]}  #${random.long} ${random.uuid} ${random.int(10)} ${random.int[1024,65536]}
#  address: 北京市

#SpringBoot slf4j默认与Logback日志框架集成，默认info级别 (但在Java中，Log4j2框架的性能是最强的，所以我们一般在程序中使用Log4j2框架)
logging:
  # 使用文件配置logback
  #config: classpath:log/logback.xml
  config: classpath:log/log4j2.xml
  #非文件配置
  #level:
      #root: debug
  # 在不指定路径，只指定输出日志的文件名，默认输出至当前项目下,若指定，则会输出至指定目录下
  #path: D:/logs
  #file: spring_boot

mybatis: 
  mapper-locations: classpath*:com/boot/**/mapper/**/*.xml
  #config-location: classpath:mybatis-config.xml  #在配置mybatis configuration 之后就不能再有此配置项，
  #否则报Property 'configuration' and 'configLocation' can not specified with together
  type-aliases-package: com.boot.**.entity

server:
  port: 8081  #自定义监听端口,默认8080
  servlet:
    context-path: /adolesce_boot #配置项目名

person:
  name: 李四
  age: 12
  address: 北京市
 
spring:
  profiles:
    #active: dev #可永于指定用哪个配置文件  application-{active}.yml or application-{active}.properties
    active:
      - dev




---
# 测试环境配置 
spring:
  profiles: test
  #热部署
  devtools:
    restart:
      #热部署开关，false即不启用热部署
      enabled: true 
      #指定目录不更新
      exclude: test/**
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mydatabase?characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 10
      minIdle: 30
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false           
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
    #schema: database/data.sql
    #sql-script-encoding: utf-8
  thymeleaf: 
     cache: false
  #SpringBootAdmin监控配置(参考：https://www.cnblogs.com/ityouknow/p/8440455.html)
  boot:
    admin:
     url: http://localhost:8000/spring-boot-admin-server
  jpa:
    properties:
       hibernate:
          hbm2ddl:
            auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true       
    #hibernate:
       #ddl-auto: none
    #tomcat:
      #max-active: 20
      #initial-size: 1
      #min-idle: 3
      #max-wait: 60000
  redis:
    #host: 192.168.90.113
    #port: 6011
    #password: Puv9pksm4Ekg
    database: 0             #数据库索引（默认为0）
    host: 192.168.1.102    #服务器地址
    port: 6379              #服务器连接端口
    password: lwd               #密码 (没有不填) 
    timeout: 60000ms          #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 500       #连接池最大连接数（使用负值表示没有限制）
        max-idle: 100         #连接池中的最大空闲连接
        min-idle: 0           #连接池中的最小空闲连接
        max-wait: 1000ms        #连接池最大阻塞等待时间（使用负值表示没有限制）
  rabbitmq: 
    #host: 192.168.90.121
    #port: 15601
    #username: rabbitmq
    #password: Puv9pksm4Ekg
    host: 192.168.1.102
    port: 5672
    username: lwd
    password: lwd
  servlet:
    encoding:
      charset: UTF-8 #防止@Value自动注入   中文乱码
    multipart:
      enabled: true  #默认支持文件上传.
      file-size-threshold: 0 #支持文件写入磁盘.
      location: D://filetest/ # 上传文件的临时目录
      max-file-size: 15MB   # 单个文件最大支持上传大小
      max-request-size: 15MB  # 总数最大支持上传大小
  mail:
    host: smtp.qiye.163.com
    username: service@51kxd.cn
    password: 1QAZ2wsx
    default-encoding: UTF-8

#actuator监控配置(参考：https://www.cnblogs.com/ityouknow/p/8423590.html)
management:
  server:
    security:
      enabled: false #默认有一部分信息需要安全验证之后才可以查看  可关掉安全认证
    port: 8088 #管理端口调整成8088
    context-path: /monitor #actuator的访问路径     启用单独的url地址来监控Spring Boot应用
  endpoints:
    shutdown:
      enabled: true #启用接口关闭Spring Boot
      sensitive: false
info:
   app:
      name: spring-boot-actuator
      version: 1.0.0    #http://localhost:8088/monitor/info
person:
     name: 李四00
     age: 1000
     address: 北京市

